/*
 * TestModelPartida.java
 *
 * Created on 21 de noviembre de 2007, 14:49
 *
 * To change this template, choose Tools | Template Manager
 * and open the template in the editor.
 */

package TestModelPartida;
import junit.framework.*;
/**
 *
 * @author Juanjito
 */
public class TestModelPartida extends TestCase {
    
    /** Creates a new instance of TestModelPartida */
    public TestModelPartida(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("Test de Partida");
        suite.addTest(AlfilTest.suite());
        suite.addTest(CaballoTest.suite());
        suite.addTest(CasillaTest.suite());
        suite.addTest(PartidaTest.suite());
        suite.addTest(PeonTest.suite());
        suite.addTest(DamaTest.suite());
        suite.addTest(ReyTest.suite());
        suite.addTest(TableroTest.suite());
        suite.addTest(TorreTest.suite());
        
           return suite;
    }
    
    
}
