/*
 * TestSuite.java
 *
 * Created on 21 de noviembre de 2007, 14:05
 *
 * To change this template, choose Tools | Template Manager
 * and open the template in the editor.
 */

package TestModelPartida;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite.*;

/**
 *
 * @author JuanjitoTestSuite
 */
public class TestSuite extends TestCase {
    
    public TestSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("ModelPartida");

        
        
        return suite;
    }
    
}